export const FETCH_CURRENT_USER = 'fetch current user'
export const FETCH_STOCK_LIST = 'fetch stock list'
export const FETCH_STOCK_ALERTS = 'fetch stock alerts'
export const ADD_STOCK_ALERT = 'add stock alert'
export const UPDATE_STOCK_ALERT = 'update stock alert'
export const DELETE_STOCK_ALERT = 'delete stock alert'
